### ISSUE TITLE
Generics support for model and generation

### ISSUE THREAD

**Issue by Pindwin** [UnityMVR/umvr#15]
Right now, the only generic types we allow for properties are `IList<>` and `ICommand<>`. The reason is simplicity: when generating code, we need to be able to establish the concrete types the interface will translate to. With such limitation, we can just manually write template code that will serve those very specific cases.

But maybe we could actually allow generics, provided the interface informs us (using attributes), what would be the underlying type of property behind the interface? E.x. we allow a property of type `IInterfaceType<TGenericType>`, but it needs an attibute, e.x. `[Collection(typeof(HashSet))]` or `[GenericDefinition(typeof(CustomUserClass<>))]`.

**Comment by Melesar** [comment]
You need to tell me what is the exact problem with using generics other than lists and commands, because I don't really get it

**Comment by Pindwin** [comment]
The `IModel` descendant interface is used to generate `Model` class (duh!). Its interface is preserved - meaning, if the interface has a `float Foo {get; set;}`, so will have the Model class - but it won't be a simple auto property, it'll have instead a backing field of type `ReactiveProperty<float>`.

Collections are special though - if we have e.x. the property of type `IList<float>`, we do not want `ReactiveProperty<IList<float>>` - what we want instead is `ReactiveCollection<float>`.

But what about `IDictionary<int, SomeCustomStruct>`? How do we decide on how to treat them? Sure, we could just mash them into `ReactiveProperty` - but that's hardly a solution. To generalise a problem, some types - usually generics - need special treatment when generating backing fields. Note, that it also affects the API of the `Model` class itself - it has separate methods for `GetProperty` and `GetCollection`.

The current approach is to just disallow generic properties, with the exception of two special cases that have their custom treatment described: `ICommand<>` and `IList<>`. But I was thinking - maybe we could just relegate responsibility for providing the correct underlying type to the user?
