### ISSUE TITLE
Model.Dispose for ModelCollectionProperty - define and implement correct behaviour

### ISSUE THREAD

**Issue by Pindwin** [UnityMVR/umvr#15]
What happens to model, when it's disposed and it's held by `IModelCollection`? Since `IModel` announces its disposal by calling `Disposing`, we should probably react to that (as we expect consumers of UMVR to do so). But what would be the correct behaviour? Removing the entry entirely? Nulling it?

**Comment by Melesar** [comment]
I don't think that smashing null in the middle of a collection is a good idea. This will blow people off even harder. 

Removing the model from all collections that are holding it sounds reasonable, but there are two considerations:

- Ideally, the user shouldn't think about it - it should be removed automatically from both the repository and all `ModelCollectionProperities`
- However, one should be careful as removing an item from the collection inside a `foreach` loop is a bad thing. So on the other hand, the user does need to think about it. 

I still think it's a better solution than just leaving null in the collection though. Perhaps we could think about some additional `Cleanup` stage that happens at `LateUpdate`, for example, when it actually removes disposed models from collections. 

What are your thoughts?

**Comment by Pindwin** [comment]
Mhm, I have been convinced to not mash null in. And removing a model from a collection always was a go-to solution for me - so let's try to consider a correct approach of doing that.

1. No action from user - sure, that's obvious. They can react to that using 'Repository.OnModelRemoved', 'Model Collection.ObserveRemove' and 'Model. Disposing' event - but that could suffer from not being clear as to what will be called first. Whatever the option though, user doesn't _need_ to do anything.
2. Regarding the option - maybe custom event in collection? Like 'Collection.ObserveMemberDisposing'? (going alongside 'Collection.ObserveRemove' anyway) That could make it slightly more clear.
3. Foreach - yeah, that's an issue - but I think it's OK to blow up an exception in the users face, as long as it happens immediately when calling dispose. I'd rather fix the issue by adding a built-in 'Custodian' object you can relegate disposing to by calling sth along the lines 'MarkForDisposal' - and then _this_ would work in Update (but that's part of completely different discussion and quite possibly, different package, as this should be part of some sort of TickManager)

**Comment by Melesar** [comment]
Can we guarantee the execution order of the events? I think if we can tell the user "hey, this is what will be called first and this is what is last" it should be enough.  However, adding another event like `ObserveMemberDisposing` can make things more confusing. I'm also not sure what is the circumstance where one would need such a distinction

**Comment by Pindwin** [comment]
Right now, I'm not sure we can. Things react to `Model.Disposing` internally. This could be fixed by introducing additional `internal` event. Another option could be the `Factory` injecting each `Model` with cleanup code that will remove it from `Repository`.
By the way, the way I see it , this would be correct order anyway:
```
- Dispose is called
-- Model.Disposing is fired - user can react in other systems, but the object is still "existing"
-- Repository.Remove is called - which initiates removal of object from internal systems
--- All collections containing disposed model remove it. This triggers collection changed events. Object is still "existing" and can be reached from repository.
--- Object is pulled out from repository
--- Repository raises event `ModelRemoved`, passing diposed model as parameter. This is the last chance to interact with it in any way before it gets invalidated - but it's already inaccessible in repository.
-- Object gets invalidated (this will require special `Id` value and possibly `model.IsValid` method or extension)
- Dispose end execution (model.Disposed event fires if we ever need one)
```

Assuming we can enforce it, the object removal from collections would be correct, right?*

* - provided, we can also ensure model not getting injected into anything during disposal. I smell `internal bool IsDisposing {get; private set}`

**Comment by Melesar** [comment]
As long as it's `internal`, that's fine :) This sequence of events sounds legit 👍
